name: "Release Packages"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and setup enviornment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev fakeroot make gcc libftdi-dev libusb-1.0-0-dev hostname git
          cd deb
          mkdir -p $GITHUB_WORKSPACE/deb/chromium-ectool/usr/bin
          mkdir -p $GITHUB_WORKSPACE/deb/cbmem/usr/bin

      - name: build ectool from source
        run: |
          curl -L https://github.com/coreboot/chrome-ec/archive/refs/heads/release-R100-14526.B-main.tar.gz -o ectool.tar.gz
          tar -xvzf ectool.tar.gz
          mv chrome-ec-release-R100-14526.B-main ectool
          cd ectool
          BOARD=host make utils-host
          cp build/host/util/ectool $GITHUB_WORKSPACE/deb/chromium-ectool/usr/bin/ectool
          cd ../
      - name: build cbmem from source
        run: |
          git clone https://github.com/coreboot/coreboot.git
          cd coreboot/util/cbmem
          make
          cp cbmem $GITHUB_WORKSPACE/deb/cbmem/usr/bin/cbmem

      - name: Build .deb packages
        run: |
          cd $GITHUB_WORKSPACE/deb
          chmod a+x chromium-ectool/usr/bin/ectool
          chmod a+x cbmem/usr/bin/cbmem
          dpkg-deb --build chromium-ectool
          dpkg-deb --build cbmem
          mv chromium-ectool.deb ../chromium-ectool.deb
          mv cbmem.deb ../cbmem.deb

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: chromium-tools
          name: "chromium-tools"
          draft: false
          prerelease: false
          files: |
            chromium-ectool.deb
            cbmem.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
